template: Hello, %s!

server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001


# Database settings.
database:
    # the name of your JDBC driver
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: 
    # the JDBC URL
    url: jdbc:mysql://localhost:3306/tenzo?useSSL=false
    # Hibernate properties
    properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate.show_sql: true
        hibernate.generate_statistics: false
        hibernate.hbm2ddl.auto: create
        packagesToScan: fr.louis.dropwizard_tenzo.core
        current_session_context_class: thread